[build]
  # Use npm ci for reproducible installs and include devDependencies so build tools (vite) are available
  command = "cd frontend && npm ci --include=dev && npm run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  # Ensure devDependencies (like vite) are installed during the build
  NPM_FLAGS = "--include=dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
